# Source: consul/templates/ui-service.yaml
# UI Service for Consul Server
apiVersion: v1
kind: Service
metadata:
  name: tf-k8s-test-consul-ui
  namespace: consul
  labels:
    app: consul
    chart: consul-helm
    heritage: Helm
    release: tf-k8s-test
    component: ui
spec:
  selector:
    app: consul
    release: "tf-k8s-test"
    component: server
  ports:
    - name: http
      port: 80
      targetPort: 8500
